// sidebarsAi.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // The key here can be anything, but 'tutorialSidebar' is common.
    // It will be the default sidebar for the 'ai' module.
    tutorialSidebar: [
        {
            type: 'autogenerated',
            dirName: '.', // '.' means 'all content in the docs/ai folder'
        },
    ],
};

module.exports = sidebars;