// sidebarsDsa.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    tutorialSidebar: [
        {

            type: 'autogenerated',
            dirName: '.', // '.' means 'all content in the docs/dsa folder'
        },
    ],
};

module.exports = sidebars;